#!/bin/sh
set -e

file="/usr/share/postgres/done.init"

_initDB() {
	count=4
	while [ "$count" -gt 0 ]; do
		psql -U postgres -f /docker-entrypoint-initdb.d/init.sql
		count=$((count-1))
		sleep 2
	done

	[ "$count" -lt 1 ] || return 1
}

[ -f "$file" ] || {
	su postgres -c docker-entrypoint.sh postgres
	_initDB || exit 1
	touch "$file"
}

exec su postgres -c docker-entrypoint.sh postgres
